# Generated by Django 5.0.2 on 2024-10-01 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_alter_user_email_alter_user_id_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
