# Generated by Django 5.0.2 on 2024-10-21 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0006_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='github_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='linkedin_url',
            field=models.URLField(),
        ),
    ]
