# Generated by Django 5.0.2 on 2024-11-04 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0007_alter_userprofile_github_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(related_name='followers', to='routes.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(related_name='following', to='routes.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='github_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
    ]
