# Generated by Django 5.1.2 on 2024-12-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0008_user_bio_user_followers_user_following_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profilepictures/'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
